resources:
  - manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: staticroute-operator
    newName: registry.smtx.io/kubesmart-dev/staticroute-operator
    newTag: v0.0.0
